### ISSUE TITLE
Support of hstore -> linked map

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/atum-service#49]
## Background
Currently Postgres' `HStore` is translated into Scala as `Map`.

## Feature
Figure out a way how to make it translated into `LinkedMap`, because the order of the keys matter.

**Comment by lsulak** [comment]
This approach might not gonna work in all the circumstances, Hstore does not guarantee the order of the records to be based on insertion-order (especially UPDATE operations might cause problems with the original order).

This means that the usage of LinkedMap would not help since the underlying DB type doesn't guarantee this.

We'll have to represent the partition-related column in a different way. A new set of tickets will be created, thus closing this one.
